### ISSUE TITLE
Crash when I tried to waypoint the skybox in Shacklethorne

### ISSUE THREAD

**Issue by loosepolygon** [HugoZink/PD2_BetterJokers#1]
offline, quick test at start of mission

weird crashlog, no mod files in stack: [crash.txt](https://github.com/HugoZink/PD2_BetterJokers/files/5250363/crash.txt)

script log ends with a fatal error: [2020_09_19_log.txt](https://github.com/HugoZink/PD2_BetterJokers/files/5250380/2020_09_19_log.txt)

(TestStuff is a small thing that edits CriminalActionWalk to make AI carry bags faster)

**Comment by morerokk** [comment]
This should be fixed now. I ran into the same issue. Thanks for your report!
