### ISSUE TITLE
Better Jokers/Project DEADLOCKE Convert Crash

### ISSUE THREAD

**Issue by VieraLaMachinist** [HugoZink/PD2_BetterJokers#2]
Game will CTD when trying to convert a Joker.

Crash date: 9/20/2020 10:19:27 AM

PAYDAY 2 Crash log
Application has crashed: C++ exception
mods/BetterJokers/lua/groupaistatebase.lua:15: attempt to index field '_unit' (a nil value)
SCRIPT STACK
Run() @mods/base/req/core/Hooks.lua:268
convert_hostage_to_criminal() @mods/PocoHud3/poco/../poco/Hud3.lua:2456
_IntimitateInteractionExt_interact() lib/units/interactions/interactionext.lua:1734
interact() @mods/DEADLOCKE/Lua/DEADLOCKE_interactionext.lua:92
end_action_interact() lib/managers/objectinteractionmanager.lua:86
_end_action_interact() lib/units/beings/player/states/playerstandard.lua:2420
_update_interaction_timers() lib/units/beings/player/states/playerstandard.lua:2464
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:871
original() lib/units/beings/player/states/playerstandard.lua:435
original() @mods/base/req/core/Hooks.lua:188
_PlayerStandard_update() @mods/base/req/core/Hooks.lua:265
update_original() @mods/DEADLOCKE/Lua/DEADLOCKE_playerstandard.lua:29
update() @mods/IRE AND FIST REBORN/lua/BurstFire.lua:350
original() lib/units/beings/player/playermovement.lua:271
@mods/base/req/core/Hooks.lua:265
-------------------------------
Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     
-------------------------------
Current thread: Main
-------------------------------
System information:
	Application version : 1.96.909
	CPU : Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1080 / nvldumd.dll[27.21.14.5206]
	Language : english
	Memory :     16342MB 536KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek(R) Audio))

**Comment by morerokk** [comment]
Pretty sure this isn't a DEADLOCKE issue. I'm pushing a fix now.

**Comment by morerokk** [comment]
This bug was related to turning on "exclusive access" in the mod options, which I maybe should have tested a little bit more (mod is heavily WIP). Thanks for your report!
